// Generated by CoffeeScript 1.8.0
(function() {
  var async, express, request, router;

  express = require('express');

  router = express.Router();

  request = require('request');

  async = require('async');


  /* GET home page. */

  router.get('/', function(req, res, next) {
    res.render('index', {
      title: 'Express'
    });
  });

  router.get('/auth', function(req, res) {
    var codeUrl, form, key, op, redirect_uri;
    key = process.env.pocket;
    console.log(key);
    codeUrl = 'https://getpocket.com/v3/oauth/request';
    redirect_uri = 'http://localhost:3000/oauth_callback';
    form = {
      'consumer_key': key,
      'redirect_uri': redirect_uri
    };
    op = {
      url: codeUrl,
      form: form
    };
    return async.auto({
      getCode: function(cb) {
        return request.post(op, function(err, response, body) {
          var code;
          if (err) {
            return console.log(err);
          }
          if (response.statusCode === 200) {
            code = body.split('=')[1];
            return cb(null, code);
          } else {
            return console.log("get code error, body", body);
          }
        });
      },
      directUrl: [
        'getCode', function(cb, result) {
          var code, url;
          code = result.getCode;
          req.session.code = code;
          url = "https://getpocket.com/auth/authorize?request_token=" + code + "&redirect_uri=" + redirect_uri;
          return res.redirect(url);
        }
      ]
    });
  });

  router.get('/oauth_callback', function(req, res) {
    var form, key, op, url;
    url = 'https://getpocket.com/v3/oauth/authorize';
    key = process.env.pocket;
    form = {
      consumer_key: key,
      code: req.session.code,
      headers: {
        'Content-Type': 'application/json; charset=UTF-8'
      }
    };
    op = {
      url: url,
      form: form
    };
    return request.post(op, function(err, response, body) {
      if (err) {
        return console.log(err);
      }
      return console.log(body);
    });
  });

  router.get('/add', function(req, res) {
    var form, op;
    form = {
      url: 'http://youqingkui.me',
      title: 'youqing-pocket',
      tags: 'youqing',
      consumer_key: process.env.pocket,
      access_token: process.env.access_token_pocket
    };
    op = {
      url: 'https://getpocket.com/v3/add',
      form: form
    };
    return request.post(op, function(err, response, body) {
      if (err) {
        return console.log(err);
      }
      return res.send(body);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
